In [ ]:
# Walmart Retail Sales Analysis

## Python Phase

### Project Objective
Analyze Walmart retail sales data using Python and generate
business-focused insights for portfolio development.

### Tools
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- SQLAlchemy
- PostgreSQL

### Project Flow
1. PostgreSQL Connection
2. Data Extraction
3. Data Understanding
4. Data Cleaning & Validation
5. Exploratory Data Analysis
6. Business Analysis
7. Visualization
8. Business Insights
9. Final Portfolio Outputs

In [1]:
# =====================================================
# STEP 1 — IMPORT REQUIRED LIBRARIES
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import psycopg2
from sqlalchemy import create_engine, text

print("All required libraries imported successfully!")

All required libraries imported successfully!

In [4]:
# =====================================================
# STEP 2 — POSTGRESQL DATABASE CONFIGURATION
# =====================================================

DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "walmart_sales_analysis"
DB_USER = "postgres"

print("PostgreSQL configuration loaded successfully!")
print("Host:", DB_HOST)
print("Port:", DB_PORT)
print("Database:", DB_NAME)
print("User:", DB_USER)

PostgreSQL configuration loaded successfully!
Host: localhost
Port: 5432
Database: walmart_sales_analysis
User: postgres

In [5]:
# =====================================================
# STEP 3 — ENTER POSTGRESQL PASSWORD
# =====================================================

from getpass import getpass

DB_PASSWORD = getpass("Enter PostgreSQL password: ")

print("Password received successfully.")

Enter PostgreSQL password:  ········

Password received successfully.

In [6]:
# =====================================================
# STEP 4 — TEST POSTGRESQL CONNECTION
# =====================================================

try:
    connection = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        database=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )

    print("PostgreSQL connection successful!")
    print("Connected Database:", DB_NAME)

    connection.close()
    print("Connection closed successfully!")

except Exception as error:
    print("PostgreSQL connection failed.")
    print("Error:", error)

PostgreSQL connection successful!
Connected Database: walmart_sales_analysis
Connection closed successfully!

In [8]:
# =====================================================
# STEP 5 — CREATE SQLALCHEMY ENGINE
# =====================================================

from sqlalchemy import create_engine, URL

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME
)

engine = create_engine(connection_url)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [9]:
# =====================================================
# STEP 6 — TEST SQLALCHEMY ENGINE
# =====================================================

from sqlalchemy import text

try:
    with engine.connect() as connection:
        result = connection.execute(
            text("SELECT current_database();")
        )
        database_name = result.scalar()

    print("SQLAlchemy connection successful!")
    print("Connected Database:", database_name)

except Exception as error:
    print("SQLAlchemy connection failed.")
    print("Error:", error)

SQLAlchemy connection successful!
Connected Database: walmart_sales_analysis

In [10]:
# =====================================================
# STEP 7 — CHECK DATABASE TABLES
# =====================================================

query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

tables_df = pd.read_sql(query, engine)

print("Tables found in PostgreSQL:")
display(tables_df)

Tables found in PostgreSQL:

               table_name
0          walmart_master
1  walmart_master_staging

In [11]:
# =====================================================
# STEP 8 — CHECK MAIN TABLE STRUCTURE
# =====================================================

query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'walmart_master'
ORDER BY ordinal_position;
"""

structure_df = pd.read_sql(query, engine)

print("Walmart Master Table Structure:")
display(structure_df)

Walmart Master Table Structure:

     column_name  data_type
0          store    integer
1           dept    integer
2           date       date
3   weekly_sales    numeric
4      isholiday    boolean
5    temperature    numeric
6     fuel_price    numeric
7      markdown1    numeric
8      markdown2    numeric
9      markdown3    numeric
10     markdown4    numeric
11     markdown5    numeric
12          type  character
13          size    integer

In [12]:
# =====================================================
# STEP 9 — LOAD WALMART DATA INTO PANDAS
# =====================================================

query = """
SELECT *
FROM walmart_master;
"""

walmart_df = pd.read_sql(query, engine)

print("Walmart data loaded successfully!")
print("Rows:", walmart_df.shape[0])
print("Columns:", walmart_df.shape[1])

Walmart data loaded successfully!
Rows: 421570
Columns: 14

In [13]:
# =====================================================
# STEP 10 — VIEW FIRST 5 ROWS
# =====================================================

display(walmart_df.head())

,store,dept,date,weekly_sales,isholiday,temperature,fuel_price,markdown1,markdown2,markdown3,markdown4,markdown5,type,size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,A,151315
1,1,2,2010-02-05,50605.27,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,A,151315
2,1,3,2010-02-05,13740.12,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,A,151315
3,1,4,2010-02-05,39954.04,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,A,151315
4,1,5,2010-02-05,32229.38,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,A,151315

In [14]:
# =====================================================
# STEP 11 — CHECK DATA TYPES
# =====================================================

print("Data Types:")
print()

walmart_df.info()

Data Types:

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store         421570 non-null  int64
 1   dept          421570 non-null  int64
 2   date          421570 non-null  object
 3   weekly_sales  421570 non-null  float64
 4   isholiday     421570 non-null  bool
 5   temperature   421570 non-null  float64
 6   fuel_price    421570 non-null  float64
 7   markdown1     421570 non-null  float64
 8   markdown2     421570 non-null  float64
 9   markdown3     421570 non-null  float64
 10  markdown4     421570 non-null  float64
 11  markdown5     421570 non-null  float64
 12  type          421570 non-null  str
 13  size          421570 non-null  int64
dtypes: bool(1), float64(8), int64(3), object(1), str(1)
memory usage: 42.6+ MB

In [15]:
# =====================================================
# STEP 12 — CONVERT DATE COLUMN TO DATETIME
# =====================================================

walmart_df["date"] = pd.to_datetime(walmart_df["date"])

print("Date column converted successfully!")
print("Date Data Type:", walmart_df["date"].dtype)

Date column converted successfully!
Date Data Type: datetime64[s]

In [16]:
# =====================================================
# STEP 13 — CHECK MISSING VALUES
# =====================================================

missing_values = walmart_df.isnull().sum()

print("Missing Values by Column:")
display(missing_values.to_frame(name="Missing_Count"))

Missing Values by Column:

              Missing_Count
store                     0
dept                      0
date                      0
weekly_sales              0
isholiday                 0
temperature               0
fuel_price                0
markdown1                 0
markdown2                 0
markdown3                 0
markdown4                 0
markdown5                 0
type                      0
size                      0

In [17]:
# =====================================================
# STEP 14 — CHECK DUPLICATE ROWS
# =====================================================

duplicate_count = walmart_df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [18]:
# =====================================================
# STEP 15 — CHECK UNIQUE VALUES
# =====================================================

print("Unique Store Types:")
print(walmart_df["type"].unique())

print("\nUnique Holiday Values:")
print(walmart_df["isholiday"].unique())

print("\nNumber of Stores:", walmart_df["store"].nunique())
print("Number of Departments:", walmart_df["dept"].nunique())

Unique Store Types:
<ArrowStringArray>
['A', 'B', 'C']
Length: 3, dtype: str

Unique Holiday Values:
[False  True]

Number of Stores: 45
Number of Departments: 81

In [19]:
# =====================================================
# STEP 16 — BASIC NUMERIC SUMMARY
# =====================================================

numeric_summary = walmart_df[
    [
        "weekly_sales",
        "temperature",
        "fuel_price",
        "size"
    ]
].describe()

display(numeric_summary)

        weekly_sales    temperature     fuel_price           size
count  421570.000000  421570.000000  421570.000000  421570.000000
mean    15981.258123      60.090059       3.361027  136727.915739
std     22711.183519      18.447931       0.458515   60980.583328
min     -4988.940000      -2.060000       2.472000   34875.000000
25%      2079.650000      46.680000       2.933000   93638.000000
50%      7612.030000      62.090000       3.452000  140167.000000
75%     20205.852500      74.280000       3.738000  202505.000000
max    693099.360000     100.140000       4.468000  219622.000000

In [20]:
# =====================================================
# STEP 17 — CHECK NEGATIVE AND ZERO SALES
# =====================================================

negative_sales = (walmart_df["weekly_sales"] < 0).sum()
zero_sales = (walmart_df["weekly_sales"] == 0).sum()

print("Negative Weekly Sales:", negative_sales)
print("Zero Weekly Sales:", zero_sales)

Negative Weekly Sales: 1285
Zero Weekly Sales: 73

In [21]:
# =====================================================
# STEP 18 — CHECK DATE RANGE
# =====================================================

min_date = walmart_df["date"].min()
max_date = walmart_df["date"].max()

print("Minimum Date:", min_date)
print("Maximum Date:", max_date)

Minimum Date: 2010-02-05 00:00:00
Maximum Date: 2012-10-26 00:00:00

In [22]:
# =====================================================
# STEP 19 — CHECK TOTAL WEEKLY SALES
# =====================================================

total_sales = walmart_df["weekly_sales"].sum()

print("Total Weekly Sales:", round(total_sales, 2))

Total Weekly Sales: 6737218987.11

In [23]:
# =====================================================
# STEP 20 — CHECK AVERAGE WEEKLY SALES
# =====================================================

average_sales = walmart_df["weekly_sales"].mean()

print("Average Weekly Sales:", round(average_sales, 2))

Average Weekly Sales: 15981.26

In [24]:
# =====================================================
# STEP 21 — CHECK MINIMUM & MAXIMUM SALES
# =====================================================

min_sales = walmart_df["weekly_sales"].min()
max_sales = walmart_df["weekly_sales"].max()

print("Minimum Weekly Sales:", round(min_sales, 2))
print("Maximum Weekly Sales:", round(max_sales, 2))

Minimum Weekly Sales: -4988.94
Maximum Weekly Sales: 693099.36

In [25]:
# =====================================================
# STEP 22 — SALES DISTRIBUTION CHECK
# =====================================================

positive_sales = (walmart_df["weekly_sales"] > 0).sum()
zero_sales = (walmart_df["weekly_sales"] == 0).sum()
negative_sales = (walmart_df["weekly_sales"] < 0).sum()

sales_distribution = pd.DataFrame({
    "Category": ["Positive Sales", "Zero Sales", "Negative Sales"],
    "Count": [positive_sales, zero_sales, negative_sales]
})

display(sales_distribution)

         Category   Count
0  Positive Sales  420212
1      Zero Sales      73
2  Negative Sales    1285

In [26]:
# =====================================================
# STEP 23 — HOLIDAY VS NON-HOLIDAY SALES
# =====================================================

holiday_summary = (
    walmart_df
    .groupby("isholiday")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
)

holiday_summary["Holiday_Status"] = holiday_summary["isholiday"].map({
    True: "Holiday",
    False: "Non-Holiday"
})

holiday_summary = holiday_summary[
    ["Holiday_Status", "count", "mean", "sum"]
]

display(holiday_summary)

  Holiday_Status   count          mean           sum
0    Non-Holiday  391909  15901.445069  6.231919e+09
1        Holiday   29661  17035.823187  5.052996e+08

In [27]:
# =====================================================
# STEP 24 — STORE-LEVEL SALES SUMMARY
# =====================================================

store_summary = (
    walmart_df
    .groupby("store")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
    .sort_values("sum", ascending=False)
)

store_summary.columns = [
    "store",
    "record_count",
    "average_sales",
    "total_sales"
]

display(store_summary.head(10))

    store  record_count  average_sales   total_sales
19     20         10214   29508.301592  3.013978e+08
3       4         10272   29161.210415  2.995440e+08
13     14         10040   28784.851727  2.889999e+08
12     13         10474   27355.136891  2.865177e+08
1       2         10238   26898.070031  2.753824e+08
9      10         10315   26332.303819  2.716177e+08
26     27         10225   24826.984536  2.538559e+08
5       6         10211   21913.243624  2.237561e+08
0       1         10244   21710.543621  2.224028e+08
38     39          9878   21000.763562  2.074455e+08

In [28]:
# =====================================================
# STEP 25 — STORE TYPE SALES SUMMARY
# =====================================================

store_type_summary = (
    walmart_df
    .groupby("type")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
    .sort_values("sum", ascending=False)
)

store_type_summary.columns = [
    "store_type",
    "record_count",
    "average_sales",
    "total_sales"
]

display(store_type_summary)

  store_type  record_count  average_sales   total_sales
0          A        215478   20099.568043  4.331015e+09
1          B        163495   12237.075977  2.000701e+09
2          C         42597    9519.532538  4.055035e+08

In [29]:
# =====================================================
# STEP 26 — DEPARTMENT-LEVEL SALES SUMMARY
# =====================================================

department_summary = (
    walmart_df
    .groupby("dept")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
    .sort_values("sum", ascending=False)
)

department_summary.columns = [
    "department",
    "record_count",
    "average_sales",
    "total_sales"
]

display(department_summary.head(10))

    department  record_count  average_sales   total_sales
73          92          6435   75204.870531  4.839433e+08
76          95          6435   69824.423080  4.493202e+08
36          38          6435   61090.619568  3.931181e+08
60          72          6046   50566.515417  3.057252e+08
71          90          6435   45232.084488  2.910685e+08
38          40          6435   44900.702727  2.889360e+08
1            2          6435   43607.020113  2.806112e+08
72          91          6435   33687.910758  2.167817e+08
12          13          6435   30663.802634  1.973216e+08
7            8          6435   30191.263517  1.942808e+08

In [7]:
# =====================================================
# STEP 27A — TEST PYTHON KERNEL
# =====================================================

print("Python kernel is working successfully!")

Python kernel is working successfully!

In [8]:
# =====================================================
# STEP 27B — LOAD PYTHON LIBRARIES
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import psycopg2
from sqlalchemy import create_engine, text, URL

print("All Python libraries loaded successfully!")

All Python libraries loaded successfully!

In [9]:
# =====================================================
# STEP 27C — RESTORE POSTGRESQL DATABASE CONFIGURATION
# =====================================================

DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "walmart_sales_analysis"
DB_USER = "postgres"

print("PostgreSQL database configuration loaded successfully!")

PostgreSQL database configuration loaded successfully!

In [10]:
# =====================================================
# STEP 27D — ENTER POSTGRESQL PASSWORD
# =====================================================

from getpass import getpass

DB_PASSWORD = getpass("Enter PostgreSQL password: ")

print("PostgreSQL password received successfully!")

Enter PostgreSQL password:  ········

PostgreSQL password received successfully!

In [11]:
# =====================================================
# STEP 27E — CREATE SQLALCHEMY ENGINE
# =====================================================

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME
)

engine = create_engine(connection_url)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [13]:
# =====================================================
# STEP 27F — RELOAD WALMART DATA
# =====================================================

query = """
SELECT *
FROM walmart_master;
"""

walmart_df = pd.read_sql(query, engine)

print("Walmart data reloaded successfully!")
print("Rows:", walmart_df.shape[0])
print("Columns:", walmart_df.shape[1])

Walmart data reloaded successfully!
Rows: 421570
Columns: 14

In [14]:
# =====================================================
# STEP 27G — RESTORE DATE FORMAT
# =====================================================

walmart_df["date"] = pd.to_datetime(walmart_df["date"])

print("Date column restored successfully!")
print("Date Data Type:", walmart_df["date"].dtype)

Date column restored successfully!
Date Data Type: datetime64[s]

In [16]:
# =====================================================
# STEP 28 — MONTHLY SALES SUMMARY
# =====================================================

walmart_df["month"] = walmart_df["date"].dt.month

monthly_summary = (
    walmart_df
    .groupby("month")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
)

monthly_summary.columns = [
    "month",
    "record_count",
    "average_sales",
    "total_sales"
]

display(monthly_summary)

    month  record_count  average_sales   total_sales
0       1         23545   14126.075111  3.325984e+08
1       2         35526   16008.779217  5.687279e+08
2       3         38451   15416.657597  5.927859e+08
3       4         41332   15650.338357  6.468598e+08
4       5         35314   15776.337202  5.571256e+08
5       6         38137   16326.137002  6.226299e+08
6       7         40980   15861.419650  6.500010e+08
7       8         38169   16062.516933  6.130902e+08
8       9         38339   15095.886154  5.787612e+08
9      10         38362   15243.855576  5.847848e+08
10     11         23613   17491.031424  4.130157e+08
11     12         29802   19355.702141  5.768386e+08

In [17]:
# =====================================================
# STEP 29 — ADD MONTH NAME
# =====================================================

monthly_summary["month_name"] = pd.to_datetime(
    monthly_summary["month"],
    format="%m"
).dt.month_name()

monthly_summary = monthly_summary[
    [
        "month",
        "month_name",
        "record_count",
        "average_sales",
        "total_sales"
    ]
]

display(monthly_summary)

    month month_name  record_count  average_sales   total_sales
0       1    January         23545   14126.075111  3.325984e+08
1       2   February         35526   16008.779217  5.687279e+08
2       3      March         38451   15416.657597  5.927859e+08
3       4      April         41332   15650.338357  6.468598e+08
4       5        May         35314   15776.337202  5.571256e+08
5       6       June         38137   16326.137002  6.226299e+08
6       7       July         40980   15861.419650  6.500010e+08
7       8     August         38169   16062.516933  6.130902e+08
8       9  September         38339   15095.886154  5.787612e+08
9      10    October         38362   15243.855576  5.847848e+08
10     11   November         23613   17491.031424  4.130157e+08
11     12   December         29802   19355.702141  5.768386e+08

In [18]:
# =====================================================
# STEP 30 — HIGHEST & LOWEST SALES MONTH
# =====================================================

highest_sales_month = monthly_summary.loc[
    monthly_summary["total_sales"].idxmax()
]

lowest_sales_month = monthly_summary.loc[
    monthly_summary["total_sales"].idxmin()
]

print("Highest Sales Month:")
print("Month:", highest_sales_month["month_name"])
print("Total Sales:", round(highest_sales_month["total_sales"], 2))

print("\nLowest Sales Month:")
print("Month:", lowest_sales_month["month_name"])
print("Total Sales:", round(lowest_sales_month["total_sales"], 2))

Highest Sales Month:
Month: July
Total Sales: 650000977.25

Lowest Sales Month:
Month: January
Total Sales: 332598438.49

In [19]:
# =====================================================
# STEP 31 — MONTHLY SALES CONTRIBUTION %
# =====================================================

total_dataset_sales = monthly_summary["total_sales"].sum()

monthly_summary["sales_contribution_pct"] = (
    monthly_summary["total_sales"]
    / total_dataset_sales
) * 100

monthly_summary["sales_contribution_pct"] = (
    monthly_summary["sales_contribution_pct"].round(2)
)

display(
    monthly_summary[
        [
            "month_name",
            "total_sales",
            "sales_contribution_pct"
        ]
    ]
)

   month_name   total_sales  sales_contribution_pct
0     January  3.325984e+08                    4.94
1    February  5.687279e+08                    8.44
2       March  5.927859e+08                    8.80
3       April  6.468598e+08                    9.60
4         May  5.571256e+08                    8.27
5        June  6.226299e+08                    9.24
6        July  6.500010e+08                    9.65
7      August  6.130902e+08                    9.10
8   September  5.787612e+08                    8.59
9     October  5.847848e+08                    8.68
10   November  4.130157e+08                    6.13
11   December  5.768386e+08                    8.56

In [20]:
# =====================================================
# STEP 32 — MONTHLY PERFORMANCE CLASSIFICATION
# =====================================================

overall_monthly_average = monthly_summary["average_sales"].mean()

monthly_summary["performance"] = np.where(
    monthly_summary["average_sales"] > overall_monthly_average,
    "Above Average",
    "Below Average"
)

print(
    "Overall Monthly Average Sales:",
    round(overall_monthly_average, 2)
)

display(
    monthly_summary[
        [
            "month_name",
            "average_sales",
            "performance"
        ]
    ]
)

Overall Monthly Average Sales: 16034.56

   month_name  average_sales    performance
0     January   14126.075111  Below Average
1    February   16008.779217  Below Average
2       March   15416.657597  Below Average
3       April   15650.338357  Below Average
4         May   15776.337202  Below Average
5        June   16326.137002  Above Average
6        July   15861.419650  Below Average
7      August   16062.516933  Above Average
8   September   15095.886154  Below Average
9     October   15243.855576  Below Average
10   November   17491.031424  Above Average
11   December   19355.702141  Above Average

In [2]:
# =====================================================
# STEP 33A — RELOAD PANDAS
# =====================================================

import pandas as pd
import numpy as np

print("Pandas loaded successfully!")
print("Pandas Version:", pd.__version__)

Pandas loaded successfully!
Pandas Version: 3.0.3

In [3]:
# =====================================================
# STEP 33B — CHECK SQLALCHEMY ENGINE
# =====================================================

try:
    engine
    print("SQLAlchemy engine is available!")
except NameError:
    print("SQLAlchemy engine is not available.")

SQLAlchemy engine is not available.

In [4]:
# =====================================================
# STEP 33C — IMPORT SQLALCHEMY
# =====================================================

from sqlalchemy import create_engine, URL, text

print("SQLAlchemy imported successfully!")

SQLAlchemy imported successfully!

In [5]:
# =====================================================
# STEP 33D — RESTORE DATABASE CONFIGURATION
# =====================================================

DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "walmart_sales_analysis"
DB_USER = "postgres"

print("Database configuration restored successfully!")

Database configuration restored successfully!

In [6]:
# =====================================================
# STEP 33E — ENTER POSTGRESQL PASSWORD
# =====================================================

from getpass import getpass

DB_PASSWORD = getpass("Enter PostgreSQL password: ")

print("PostgreSQL password received successfully!")

Enter PostgreSQL password:  ········

PostgreSQL password received successfully!

In [7]:
# =====================================================
# STEP 33F — CREATE SQLALCHEMY ENGINE
# =====================================================

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME
)

engine = create_engine(connection_url)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [10]:
# =====================================================
# STEP 33G — RELOAD WALMART DATA
# =====================================================

query = """
SELECT *
FROM walmart_master;
"""

walmart_df = pd.read_sql(query, engine)

print("Walmart data reloaded successfully!")
print("Rows:", walmart_df.shape[0])
print("Columns:", walmart_df.shape[1])

Walmart data reloaded successfully!
Rows: 421570
Columns: 14

In [11]:
# =====================================================
# STEP 33H — STORE PERFORMANCE RANKING
# =====================================================

store_ranking = (
    walmart_df
    .groupby("store")["weekly_sales"]
    .agg(["count", "mean", "sum"])
    .reset_index()
)

store_ranking.columns = [
    "store",
    "record_count",
    "average_sales",
    "total_sales"
]

# Rank stores by total sales
store_ranking["sales_rank"] = (
    store_ranking["total_sales"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

# Overall average store sales
overall_store_average = store_ranking["total_sales"].mean()

# Performance classification
store_ranking["performance"] = np.where(
    store_ranking["total_sales"] > overall_store_average,
    "Above Average",
    "Below Average"
)

# Sort by rank
store_ranking = store_ranking.sort_values("sales_rank")

display(store_ranking.head(10))

,store,record_count,average_sales,total_sales,sales_rank,performance
19,20,10214,29508.301592,3.013978e+08,1,Above Average
3,4,10272,29161.210415,2.995440e+08,2,Above Average
13,14,10040,28784.851727,2.889999e+08,3,Above Average
12,13,10474,27355.136891,2.865177e+08,4,Above Average
1,2,10238,26898.070031,2.753824e+08,5,Above Average
9,10,10315,26332.303819,2.716177e+08,6,Above Average
26,27,10225,24826.984536,2.538559e+08,7,Above Average
5,6,10211,21913.243624,2.237561e+08,8,Above Average
0,1,10244,21710.543621,2.224028e+08,9,Above Average
38,39,9878,21000.763562,2.074455e+08,10,Above Average

In [13]:
# =====================================================
# STEP 34 — STORE TYPE × STORE PERFORMANCE ANALYSIS
# =====================================================

store_type_performance = (
    walmart_df
    .groupby("type")
    .agg(
        store_count=("store", "nunique"),
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

store_type_performance.columns = [
    "store_type",
    "store_count",
    "record_count",
    "average_sales",
    "total_sales"
]

display(store_type_performance)

  store_type  store_count  record_count  average_sales   total_sales
0          A           22        215478   20099.568043  4.331015e+09
1          B           17        163495   12237.075977  2.000701e+09
2          C            6         42597    9519.532538  4.055035e+08

In [14]:
# =====================================================
# STEP 35 — DEPARTMENT PERFORMANCE ANALYSIS
# =====================================================

department_performance = (
    walmart_df
    .groupby("dept")
    .agg(
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

# Rank departments by total sales
department_performance["sales_rank"] = (
    department_performance["total_sales"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

# Sort by sales rank
department_performance = department_performance.sort_values(
    "sales_rank"
)

display(department_performance.head(10))

    dept  record_count  average_sales   total_sales  sales_rank
73    92          6435   75204.870531  4.839433e+08           1
76    95          6435   69824.423080  4.493202e+08           2
36    38          6435   61090.619568  3.931181e+08           3
60    72          6046   50566.515417  3.057252e+08           4
71    90          6435   45232.084488  2.910685e+08           5
38    40          6435   44900.702727  2.889360e+08           6
1      2          6435   43607.020113  2.806112e+08           7
72    91          6435   33687.910758  2.167817e+08           8
12    13          6435   30663.802634  1.973216e+08           9
7      8          6435   30191.263517  1.942808e+08          10

In [16]:
# =====================================================
# STEP 36 — DEPARTMENT × STORE TYPE SALES ANALYSIS
# =====================================================

department_store_type = (
    walmart_df
    .groupby(["type", "dept"])
    .agg(
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

# Rank departments within each store type
department_store_type["type_rank"] = (
    department_store_type
    .groupby("type")["total_sales"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

# Show top 5 departments for each store type
top_departments_by_type = (
    department_store_type
    .sort_values(["type", "type_rank"])
    .groupby("type")
    .head(5)
)

display(top_departments_by_type)

    type  dept  record_count  average_sales   total_sales  type_rank
73     A    92          3146  112156.881662  3.528455e+08          1
76     A    95          3146   97094.026043  3.054578e+08          2
71     A    90          3146   70550.502168  2.219519e+08          3
36     A    38          3146   65005.018090  2.045058e+08          4
60     A    72          2877   62046.661710  1.785082e+08          5
117    B    38          2431   58301.167717  1.417301e+08          1
140    B    72          2431   52294.210531  1.271272e+08          2
82     B     2          2431   43051.996919  1.046594e+08          3
119    B    40          2431   42365.556516  1.029907e+08          4
156    B    95          2431   41304.769202  1.004119e+08          5
219    C    92           858   60795.759371  5.216276e+07          1
194    C    38           858   54641.271900  4.688221e+07          2
222    C    95           858   50641.564872  4.345046e+07          3
217    C    90           858   43628.231072  3.743302e+07          4
221    C    94           858   31636.174895  2.714384e+07          5

In [18]:
# =====================================================
# STEP 37A — RESTORE MONTH COLUMN
# =====================================================

walmart_df["date"] = pd.to_datetime(walmart_df["date"])

walmart_df["month"] = walmart_df["date"].dt.month

print("Month column restored successfully!")
print("Month column exists:", "month" in walmart_df.columns)

Month column restored successfully!
Month column exists: True

In [19]:
# =====================================================
# STEP 37B — HOLIDAY vs NON-HOLIDAY MONTHLY SALES
# =====================================================

holiday_monthly = (
    walmart_df
    .groupby(["month", "isholiday"])["weekly_sales"]
    .agg(
        record_count="count",
        average_sales="mean",
        total_sales="sum"
    )
    .reset_index()
)

# Add readable month names
holiday_monthly["month_name"] = pd.to_datetime(
    holiday_monthly["month"],
    format="%m"
).dt.month_name()

# Add Holiday / Non-Holiday label
holiday_monthly["holiday_status"] = np.where(
    holiday_monthly["isholiday"],
    "Holiday",
    "Non-Holiday"
)

# Arrange columns
holiday_monthly = holiday_monthly[
    [
        "month",
        "month_name",
        "holiday_status",
        "record_count",
        "average_sales",
        "total_sales"
    ]
]

display(holiday_monthly)

    month month_name holiday_status  record_count  average_sales   total_sales
0       1    January    Non-Holiday         23545   14126.075111  3.325984e+08
1       2   February    Non-Holiday         26631   15885.457253  4.230456e+08
2       2   February        Holiday          8895   16377.996441  1.456823e+08
3       3      March    Non-Holiday         38451   15416.657597  5.927859e+08
4       4      April    Non-Holiday         41332   15650.338357  6.468598e+08
5       5        May    Non-Holiday         35314   15776.337202  5.571256e+08
6       6       June    Non-Holiday         38137   16326.137002  6.226299e+08
7       7       July    Non-Holiday         40980   15861.419650  6.500010e+08
8       8     August    Non-Holiday         38169   16062.516933  6.130902e+08
9       9  September    Non-Holiday         29478   14859.674828  4.380335e+08
10      9  September        Holiday          8861   15881.693339  1.407277e+08
11     10    October    Non-Holiday         38362   15243.855576  5.847848e+08
12     11   November    Non-Holiday         17654   15894.478108  2.806011e+08
13     11   November        Holiday          5959   22220.944538  1.324146e+08
14     12   December    Non-Holiday         23856   20555.149864  4.903637e+08
15     12   December        Holiday          5946   14543.387158  8.647498e+07

In [20]:
# =====================================================
# STEP 38 — OVERALL HOLIDAY vs NON-HOLIDAY SALES
# =====================================================

holiday_overall = (
    walmart_df
    .groupby("isholiday")["weekly_sales"]
    .agg(
        record_count="count",
        average_sales="mean",
        total_sales="sum"
    )
    .reset_index()
)

holiday_overall["holiday_status"] = np.where(
    holiday_overall["isholiday"],
    "Holiday",
    "Non-Holiday"
)

holiday_overall = holiday_overall[
    [
        "holiday_status",
        "record_count",
        "average_sales",
        "total_sales"
    ]
]

display(holiday_overall)

  holiday_status  record_count  average_sales   total_sales
0    Non-Holiday        391909   15901.445069  6.231919e+09
1        Holiday         29661   17035.823187  5.052996e+08

In [21]:
# =====================================================
# STEP 39 — STORE SIZE vs SALES ANALYSIS
# =====================================================

store_size_sales = (
    walmart_df
    .groupby(["store", "type", "size"])
    .agg(
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

# Sort by store size
store_size_sales = store_size_sales.sort_values(
    "size",
    ascending=False
)

display(store_size_sales.head(15))

    store type    size  record_count  average_sales   total_sales
12     13    A  219622         10474   27355.136891  2.865177e+08
10     11    A  207499         10062   19276.762751  1.939628e+08
27     28    A  206302         10113   18714.889803  1.892637e+08
3       4    A  205863         10272   29161.210415  2.995440e+08
26     27    A  204184         10225   24826.984536  2.538559e+08
23     24    A  203819         10228   18969.106500  1.940160e+08
18     19    A  203819         10148   20362.126734  2.066349e+08
30     31    A  203750         10142   19681.907464  1.996139e+08
19     20    A  203742         10214   29508.301592  3.013978e+08
31     32    A  203007         10202   16351.621855  1.668192e+08
5       6    A  202505         10211   21913.243624  2.237561e+08
1       2    A  202307         10238   26898.070031  2.753824e+08
13     14    A  200898         10040   28784.851727  2.889999e+08
40     41    A  196321         10088   17976.004648  1.813419e+08
38     39    A  184109          9878   21000.763562  2.074455e+08

In [22]:
# =====================================================
# STEP 40 — STORE SIZE CATEGORY ANALYSIS
# =====================================================

store_size_category = store_size_sales.copy()

store_size_category["size_category"] = pd.cut(
    store_size_category["size"],
    bins=[0, 100000, 180000, float("inf")],
    labels=["Small", "Medium", "Large"]
)

size_category_summary = (
    store_size_category
    .groupby("size_category", observed=True)
    .agg(
        store_count=("store", "nunique"),
        average_store_size=("size", "mean"),
        average_sales=("average_sales", "mean"),
        total_sales=("total_sales", "sum")
    )
    .reset_index()
)

display(size_category_summary)

  size_category  store_count  average_store_size  average_sales   total_sales
0         Small           14        50703.785714    8608.996870  9.599128e+08
1        Medium           16       131583.875000   14587.949933  2.308754e+09
2         Large           15       203183.133333   22718.732142  3.468552e+09

In [23]:
# =====================================================
# STEP 41 — STORE TYPE × SIZE CATEGORY ANALYSIS
# =====================================================

store_type_size = store_size_category.copy()

type_size_summary = (
    store_type_size
    .groupby(["type", "size_category"], observed=True)
    .agg(
        store_count=("store", "nunique"),
        average_store_size=("size", "mean"),
        average_sales=("average_sales", "mean"),
        total_sales=("total_sales", "sum")
    )
    .reset_index()
)

display(type_size_summary)

,type,size_category,store_count,average_store_size,average_sales,total_sales
0,A,Small,2,39800.000000,7156.413308,9.057244e+07
1,A,Medium,5,154420.600000,15336.680507,7.718905e+08
2,A,Large,15,203183.133333,22718.732142,3.468552e+09
3,B,Small,6,64500.500000,8126.940719,4.638368e+08
4,B,Medium,11,121203.545455,14247.617854,1.536864e+09
5,C,Small,6,40541.666667,9575.247543,4.055035e+08

In [24]:
# =====================================================
# STEP 42 — TEMPERATURE vs WEEKLY SALES
# =====================================================

temperature_sales = (
    walmart_df[
        ["temperature", "weekly_sales"]
    ]
    .copy()
)

temperature_sales["temperature_range"] = pd.cut(
    temperature_sales["temperature"],
    bins=[-float("inf"), 32, 50, 70, 90, float("inf")],
    labels=[
        "Very Cold",
        "Cold",
        "Moderate",
        "Warm",
        "Very Warm"
    ]
)

temperature_summary = (
    temperature_sales
    .groupby("temperature_range", observed=True)
    .agg(
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

display(temperature_summary)

  temperature_range  record_count  average_sales   total_sales
0         Very Cold         35503   15244.417289  5.412225e+08
1              Cold         90626   16467.266267  1.492362e+09
2          Moderate        151439   15968.077447  2.418190e+09
3              Warm        133302   16062.725497  2.141193e+09
4         Very Warm         10700   13481.388102  1.442509e+08

In [25]:
# =====================================================
# STEP 43 — FUEL PRICE vs WEEKLY SALES
# =====================================================

fuel_price_sales = (
    walmart_df[
        ["fuel_price", "weekly_sales"]
    ]
    .copy()
)

fuel_price_sales["fuel_price_range"] = pd.cut(
    fuel_price_sales["fuel_price"],
    bins=[0, 2.75, 3.00, 3.50, 4.00, float("inf")],
    labels=[
        "Low",
        "Moderate-Low",
        "Moderate-High",
        "High",
        "Very High"
    ]
)

fuel_price_summary = (
    fuel_price_sales
    .groupby("fuel_price_range", observed=True)
    .agg(
        record_count=("weekly_sales", "count"),
        average_sales=("weekly_sales", "mean"),
        total_sales=("weekly_sales", "sum")
    )
    .reset_index()
)

display(fuel_price_summary)

  fuel_price_range  record_count  average_sales   total_sales
0              Low         51789   15042.713009  7.790471e+08
1     Moderate-Low         70800   16524.056810  1.169903e+09
2    Moderate-High         99318   16405.096859  1.629321e+09
3             High        173088   15825.166233  2.739146e+09
4        Very High         26575   15796.836058  4.198009e+08

In [26]:
# =====================================================
# STEP 44 — MARKDOWN IMPACT ANALYSIS
# =====================================================

markdown_columns = [
    "markdown1",
    "markdown2",
    "markdown3",
    "markdown4",
    "markdown5"
]

# Calculate total markdown
walmart_df["total_markdown"] = walmart_df[markdown_columns].sum(axis=1)

# Create markdown status
walmart_df["markdown_status"] = np.where(
    walmart_df["total_markdown"] > 0,
    "Markdown Applied",
    "No Markdown"
)

# Compare sales performance
markdown_summary = (
    walmart_df
    .groupby("markdown_status")["weekly_sales"]
    .agg(
        record_count="count",
        average_sales="mean",
        total_sales="sum"
    )
    .reset_index()
)

display(markdown_summary)

    markdown_status  record_count  average_sales   total_sales
0  Markdown Applied        151432   16177.015244  2.449718e+09
1       No Markdown        270138   15871.522017  4.287501e+09

In [28]:
# =====================================================
# STEP 45 — NEGATIVE & ZERO SALES ANALYSIS
# =====================================================

walmart_df["sales_category"] = np.select(
    [
        walmart_df["weekly_sales"] < 0,
        walmart_df["weekly_sales"] == 0,
        walmart_df["weekly_sales"] > 0
    ],
    [
        "Negative Sales",
        "Zero Sales",
        "Positive Sales"
    ],
    default="Unknown"
)

sales_quality_summary = (
    walmart_df
    .groupby("sales_category")["weekly_sales"]
    .agg(
        record_count="count",
        average_sales="mean",
        total_sales="sum"
    )
    .reset_index()
)

display(sales_quality_summary)

   sales_category  record_count  average_sales   total_sales
0  Negative Sales          1285     -68.608218 -8.816156e+04
1  Positive Sales        420212   16033.114591  6.737307e+09
2      Zero Sales            73       0.000000  0.000000e+00

In [29]:
# =====================================================
# STEP 46 — WEEKLY SALES OUTLIER ANALYSIS
# =====================================================

Q1 = walmart_df["weekly_sales"].quantile(0.25)
Q3 = walmart_df["weekly_sales"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_mask = (
    (walmart_df["weekly_sales"] < lower_bound) |
    (walmart_df["weekly_sales"] > upper_bound)
)

outlier_count = outlier_mask.sum()
normal_count = (~outlier_mask).sum()

print("Q1:", round(Q1, 2))
print("Q3:", round(Q3, 2))
print("IQR:", round(IQR, 2))

print("\nLower Bound:", round(lower_bound, 2))
print("Upper Bound:", round(upper_bound, 2))

print("\nOutlier Records:", outlier_count)
print("Normal Records:", normal_count)

Q1: 2079.65
Q3: 20205.85
IQR: 18126.2

Lower Bound: -25109.65
Upper Bound: 47395.16

Outlier Records: 35521
Normal Records: 386049

In [30]:
# =====================================================
# STEP 47 — OUTLIER SALES SUMMARY
# =====================================================

outlier_df = walmart_df[outlier_mask].copy()

outlier_summary = pd.DataFrame({
    "metric": [
        "Outlier Records",
        "Average Outlier Sales",
        "Minimum Outlier Sales",
        "Maximum Outlier Sales",
        "Total Outlier Sales"
    ],
    "value": [
        len(outlier_df),
        outlier_df["weekly_sales"].mean(),
        outlier_df["weekly_sales"].min(),
        outlier_df["weekly_sales"].max(),
        outlier_df["weekly_sales"].sum()
    ]
})

display(outlier_summary)

                  metric         value
0        Outlier Records  3.552100e+04
1  Average Outlier Sales  7.507003e+04
2  Minimum Outlier Sales  4.739557e+04
3  Maximum Outlier Sales  6.930994e+05
4    Total Outlier Sales  2.666563e+09

In [31]:
# =====================================================
# STEP 48 — CORRELATION ANALYSIS
# =====================================================

correlation_columns = [
    "weekly_sales",
    "temperature",
    "fuel_price",
    "markdown1",
    "markdown2",
    "markdown3",
    "markdown4",
    "markdown5",
    "size"
]

correlation_matrix = (
    walmart_df[correlation_columns]
    .corr()
    .round(3)
)

display(correlation_matrix)

,weekly_sales,temperature,fuel_price,markdown1,markdown2,markdown3,markdown4,markdown5,size
weekly_sales,1.000,-0.002,-0.000,0.047,0.021,0.039,0.037,0.050,0.244
temperature,-0.002,1.000,0.144,-0.026,-0.180,-0.056,-0.050,-0.015,-0.058
fuel_price,-0.000,0.144,1.000,0.297,0.029,0.019,0.167,0.215,0.003
markdown1,0.047,-0.026,0.297,1.000,0.175,-0.014,0.839,0.415,0.170
markdown2,0.021,-0.180,0.029,0.175,1.000,-0.006,0.113,0.132,0.078
markdown3,0.039,-0.056,0.019,-0.014,-0.006,1.000,-0.012,0.042,0.034
markdown4,0.037,-0.050,0.167,0.839,0.113,-0.012,1.000,0.303,0.127
markdown5,0.050,-0.015,0.215,0.415,0.132,0.042,0.303,1.000,0.153
size,0.244,-0.058,0.003,0.170,0.078,0.034,0.127,0.153,1.000

In [32]:
# =====================================================
# STEP 49 — FINAL PYTHON KPI SUMMARY
# =====================================================

total_sales = walmart_df["weekly_sales"].sum()
average_sales = walmart_df["weekly_sales"].mean()

total_records = len(walmart_df)
total_stores = walmart_df["store"].nunique()
total_departments = walmart_df["dept"].nunique()

minimum_sales = walmart_df["weekly_sales"].min()
maximum_sales = walmart_df["weekly_sales"].max()

negative_sales_count = (walmart_df["weekly_sales"] < 0).sum()
zero_sales_count = (walmart_df["weekly_sales"] == 0).sum()

holiday_average = (
    walmart_df.loc[
        walmart_df["isholiday"] == True,
        "weekly_sales"
    ].mean()
)

non_holiday_average = (
    walmart_df.loc[
        walmart_df["isholiday"] == False,
        "weekly_sales"
    ].mean()
)

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Records",
        "Total Stores",
        "Total Departments",
        "Total Weekly Sales",
        "Average Weekly Sales",
        "Minimum Weekly Sales",
        "Maximum Weekly Sales",
        "Negative Sales Records",
        "Zero Sales Records",
        "Holiday Average Sales",
        "Non-Holiday Average Sales"
    ],
    "Value": [
        total_records,
        total_stores,
        total_departments,
        total_sales,
        average_sales,
        minimum_sales,
        maximum_sales,
        negative_sales_count,
        zero_sales_count,
        holiday_average,
        non_holiday_average
    ]
})

display(kpi_summary)

                          KPI         Value
0               Total Records  4.215700e+05
1                Total Stores  4.500000e+01
2           Total Departments  8.100000e+01
3          Total Weekly Sales  6.737219e+09
4        Average Weekly Sales  1.598126e+04
5        Minimum Weekly Sales -4.988940e+03
6        Maximum Weekly Sales  6.930994e+05
7      Negative Sales Records  1.285000e+03
8          Zero Sales Records  7.300000e+01
9       Holiday Average Sales  1.703582e+04
10  Non-Holiday Average Sales  1.590145e+04

In [33]:
# =====================================================
# STEP 50 — KEY BUSINESS INSIGHTS
# =====================================================

print("========== KEY BUSINESS INSIGHTS ==========\n")

print(
    f"1. Total sales generated across the dataset: "
    f"${total_sales:,.2f}"
)

print(
    f"2. Average weekly sales: "
    f"${average_sales:,.2f}"
)

print(
    f"3. Dataset covers {total_stores} stores "
    f"and {total_departments} departments."
)

print(
    f"4. Holiday average sales (${holiday_average:,.2f}) "
    f"were higher than non-holiday average sales "
    f"(${non_holiday_average:,.2f})."
)

print(
    f"5. Negative sales records: "
    f"{negative_sales_count:,}"
)

print(
    f"6. Zero sales records: "
    f"{zero_sales_count:,}"
)

print(
    "7. Large stores generated higher average sales "
    "than medium and small stores."
)

print(
    "8. Store size showed a positive relationship "
    "with weekly sales, while temperature and fuel price "
    "showed almost no linear correlation with weekly sales."
)

print(
    "9. Markdown-applied records had a slightly higher "
    "average weekly sales than records without markdown."
)

print(
    "10. Monthly sales varied considerably across the year, "
    "with July recording the highest total monthly sales "
    "and January recording the lowest."
)

========== KEY BUSINESS INSIGHTS ==========

1. Total sales generated across the dataset: $6,737,218,987.11
2. Average weekly sales: $15,981.26
3. Dataset covers 45 stores and 81 departments.
4. Holiday average sales ($17,035.82) were higher than non-holiday average sales ($15,901.45).
5. Negative sales records: 1,285
6. Zero sales records: 73
7. Large stores generated higher average sales than medium and small stores.
8. Store size showed a positive relationship with weekly sales, while temperature and fuel price showed almost no linear correlation with weekly sales.
9. Markdown-applied records had a slightly higher average weekly sales than records without markdown.
10. Monthly sales varied considerably across the year, with July recording the highest total monthly sales and January recording the lowest.

In [34]:
# =====================================================
# STEP 51 — MANAGEMENT RECOMMENDATIONS
# =====================================================

recommendations = [
    "Focus on large stores because they show higher average sales performance.",
    
    "Use holiday periods for targeted promotions and inventory planning "
    "because average holiday sales are higher than non-holiday sales.",
    
    "Investigate January sales performance and identify opportunities "
    "to improve demand during the lowest-sales month.",
    
    "Prepare inventory and staffing plans for high-sales months, "
    "especially around July and other strong-performing periods.",
    
    "Monitor negative and zero sales records as potential data-quality "
    "or operational exceptions.",
    
    "Evaluate markdown campaigns using additional business factors "
    "before concluding their direct impact on sales.",
    
    "Store size should be considered as an important segmentation factor "
    "when comparing store-level sales performance.",
    
    "Temperature and fuel price should not be treated as strong standalone "
    "predictors of weekly sales based on the observed linear correlations."
]

for i, recommendation in enumerate(recommendations, start=1):
    print(f"{i}. {recommendation}\n")

1. Focus on large stores because they show higher average sales performance.

2. Use holiday periods for targeted promotions and inventory planning because average holiday sales are higher than non-holiday sales.

3. Investigate January sales performance and identify opportunities to improve demand during the lowest-sales month.

4. Prepare inventory and staffing plans for high-sales months, especially around July and other strong-performing periods.

5. Monitor negative and zero sales records as potential data-quality or operational exceptions.

6. Evaluate markdown campaigns using additional business factors before concluding their direct impact on sales.

7. Store size should be considered as an important segmentation factor when comparing store-level sales performance.

8. Temperature and fuel price should not be treated as strong standalone predictors of weekly sales based on the observed linear correlations.

In [35]:
# =====================================================
# STEP 52 — CREATE FINAL PYTHON ANALYSIS DATASET
# =====================================================

final_store_analysis = (
    walmart_df
    .groupby(["store", "type", "size"])["weekly_sales"]
    .agg(
        record_count="count",
        average_sales="mean",
        total_sales="sum"
    )
    .reset_index()
)

final_store_analysis["sales_rank"] = (
    final_store_analysis["total_sales"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

final_store_analysis = final_store_analysis.sort_values(
    "sales_rank"
)

display(final_store_analysis.head(15))

    store type    size  record_count  average_sales   total_sales  sales_rank
19     20    A  203742         10214   29508.301592  3.013978e+08           1
3       4    A  205863         10272   29161.210415  2.995440e+08           2
13     14    A  200898         10040   28784.851727  2.889999e+08           3
12     13    A  219622         10474   27355.136891  2.865177e+08           4
1       2    A  202307         10238   26898.070031  2.753824e+08           5
9      10    B  126512         10315   26332.303819  2.716177e+08           6
26     27    A  204184         10225   24826.984536  2.538559e+08           7
5       6    A  202505         10211   21913.243624  2.237561e+08           8
0       1    A  151315         10244   21710.543621  2.224028e+08           9
38     39    A  184109          9878   21000.763562  2.074455e+08          10
18     19    A  203819         10148   20362.126734  2.066349e+08          11
30     31    A  203750         10142   19681.907464  1.996139e+08          12
22     23    B  114533         10050   19776.180881  1.987506e+08          13
23     24    A  203819         10228   18969.106500  1.940160e+08          14
10     11    A  207499         10062   19276.762751  1.939628e+08          15

In [36]:
# =====================================================
# STEP 53 — EXPORT FINAL PYTHON ANALYSIS
# =====================================================

output_file = "Walmart_Final_Store_Analysis.csv"

final_store_analysis.to_csv(
    output_file,
    index=False
)

print("Final Python analysis exported successfully!")
print("File:", output_file)
print("Rows:", len(final_store_analysis))
print("Columns:", len(final_store_analysis.columns))

Final Python analysis exported successfully!
File: Walmart_Final_Store_Analysis.csv
Rows: 45
Columns: 7

In [37]:
# =====================================================
# STEP 54 — CREATE PYTHON PROJECT DOCUMENTATION
# =====================================================

project_documentation = f"""
WALMART RETAIL SALES ANALYSIS
Python Analysis Documentation
========================================

PROJECT OBJECTIVE
-----------------
Analyze Walmart retail sales data to identify sales patterns,
store performance, seasonal trends, holiday impact, and
key business insights.

DATASET OVERVIEW
----------------
Total Records: {total_records:,}
Total Stores: {total_stores}
Total Departments: {total_departments}
Minimum Date: {walmart_df["date"].min().date()}
Maximum Date: {walmart_df["date"].max().date()}

KEY KPIs
--------
Total Weekly Sales: ${total_sales:,.2f}
Average Weekly Sales: ${average_sales:,.2f}
Minimum Weekly Sales: ${minimum_sales:,.2f}
Maximum Weekly Sales: ${maximum_sales:,.2f}
Negative Sales Records: {negative_sales_count:,}
Zero Sales Records: {zero_sales_count:,}

HOLIDAY ANALYSIS
----------------
Holiday Average Sales: ${holiday_average:,.2f}
Non-Holiday Average Sales: ${non_holiday_average:,.2f}

PYTHON ANALYSIS COMPLETED
-------------------------
1. Data Validation
2. Missing Value Analysis
3. Duplicate Analysis
4. Store Performance Analysis
5. Store Type Analysis
6. Department Analysis
7. Monthly Sales Analysis
8. Holiday Analysis
9. Store Size Analysis
10. Temperature Analysis
11. Fuel Price Analysis
12. Markdown Analysis
13. Negative and Zero Sales Analysis
14. Outlier Analysis
15. Correlation Analysis

KEY BUSINESS INSIGHTS
---------------------
1. Large stores showed higher average sales performance.
2. Holiday average sales were higher than non-holiday average sales.
3. July recorded the highest total monthly sales.
4. January recorded the lowest total monthly sales.
5. Store size showed a positive relationship with weekly sales.
6. Temperature showed almost no linear correlation with weekly sales.
7. Fuel price showed almost no linear correlation with weekly sales.
8. Markdown-applied records had slightly higher average sales.
9. Negative and zero sales records require monitoring.
10. Sales performance varied significantly across stores and departments.

TOOLS USED
----------
Python
Pandas
NumPy
SQLAlchemy
PostgreSQL
Jupyter Notebook
"""

print(project_documentation)

WALMART RETAIL SALES ANALYSIS
Python Analysis Documentation
========================================

PROJECT OBJECTIVE
-----------------
Analyze Walmart retail sales data to identify sales patterns,
store performance, seasonal trends, holiday impact, and
key business insights.

DATASET OVERVIEW
----------------
Total Records: 421,570
Total Stores: 45
Total Departments: 81
Minimum Date: 2010-02-05
Maximum Date: 2012-10-26

KEY KPIs
--------
Total Weekly Sales: $6,737,218,987.11
Average Weekly Sales: $15,981.26
Minimum Weekly Sales: $-4,988.94
Maximum Weekly Sales: $693,099.36
Negative Sales Records: 1,285
Zero Sales Records: 73

HOLIDAY ANALYSIS
----------------
Holiday Average Sales: $17,035.82
Non-Holiday Average Sales: $15,901.45

PYTHON ANALYSIS COMPLETED
-------------------------
1. Data Validation
2. Missing Value Analysis
3. Duplicate Analysis
4. Store Performance Analysis
5. Store Type Analysis
6. Department Analysis
7. Monthly Sales Analysis
8. Holiday Analysis
9. Store Size Analysis
10. Temperature Analysis
11. Fuel Price Analysis
12. Markdown Analysis
13. Negative and Zero Sales Analysis
14. Outlier Analysis
15. Correlation Analysis

KEY BUSINESS INSIGHTS
---------------------
1. Large stores showed higher average sales performance.
2. Holiday average sales were higher than non-holiday average sales.
3. July recorded the highest total monthly sales.
4. January recorded the lowest total monthly sales.
5. Store size showed a positive relationship with weekly sales.
6. Temperature showed almost no linear correlation with weekly sales.
7. Fuel price showed almost no linear correlation with weekly sales.
8. Markdown-applied records had slightly higher average sales.
9. Negative and zero sales records require monitoring.
10. Sales performance varied significantly across stores and departments.

TOOLS USED
----------
Python
Pandas
NumPy
SQLAlchemy
PostgreSQL
Jupyter Notebook

In [38]:
# =====================================================
# STEP 55 — VERIFY FINAL PYTHON EXPORT
# =====================================================

import os

output_file = "Walmart_Final_Store_Analysis.csv"

if os.path.exists(output_file):

    verified_file = pd.read_csv(output_file)

    print("Final Python export verified successfully!")
    print("File:", output_file)
    print("Rows:", verified_file.shape[0])
    print("Columns:", verified_file.shape[1])

    print("\nColumns:")
    print(list(verified_file.columns))

    print("\nFirst 5 Records:")
    display(verified_file.head())

else:
    print("ERROR: Export file not found.")

Final Python export verified successfully!
File: Walmart_Final_Store_Analysis.csv
Rows: 45
Columns: 7

Columns:
['store', 'type', 'size', 'record_count', 'average_sales', 'total_sales', 'sales_rank']

First 5 Records:

   store type    size  record_count  average_sales   total_sales  sales_rank
0     20    A  203742         10214   29508.301592  3.013978e+08           1
1      4    A  205863         10272   29161.210415  2.995440e+08           2
2     14    A  200898         10040   28784.851727  2.889999e+08           3
3     13    A  219622         10474   27355.136891  2.865177e+08           4
4      2    A  202307         10238   26898.070031  2.753824e+08           5